### ISSUE TITLE
please provide a new link about dataset

### ISSUE THREAD

**Issue by tyust-dayu** [ByronJi/DRGCL#1]
We are very interested in your work, but when running the code we found that the link to the dataset is not working, if you could provide a new link we would be very grateful!
![image](https://github.com/user-attachments/assets/7bb603b6-3270-4c2b-8bb3-df4fbae6d96d)

**Comment by ByronJi** [comment]
You can download the dataset through this link：[https://chrsmrrs.github.io/datasets/docs/datasets/](https://chrsmrrs.github.io/datasets/docs/datasets/).
